### ISSUE TITLE
Have you tried rpy2?

### ISSUE THREAD

**Issue by ralexx** [JWarmenhoven/ISLR-python#6]
I've also transcribed the *Statistical Learning* material into Python but only for my own reference. Yours is very elegant and I wish I'd discovered it at the beginning of the course rather than the end.

I noticed that you've gone to the extra step of dumping the R data to file and then loading into the Python environment in Jupyter. In my notes I wanted to have the R and Python code on top of each other for easy reference, so I [installed](https://www.continuum.io/blog/developer/jupyter-and-conda-r) an R virtualenv and [built](http://www.alfredo.motta.name/create-isolated-jupyter-ipython-kernels-with-pyenv-and-virtualenv/) a "bilingual" Jupyter kernel that handles both languages. So far I've had good results using this version of [rpy2](https://anaconda.org/bioconda/rpy2) with Python 3.5 to invoke R magics in Jupyter and intersperse the two languages in the same notebook.

See my attached notebook, in case you find it useful.
[StatLearning_Chapter4R_inPython.ipynb.zip](https://github.com/JWarmenhoven/ISLR-python/files/204039/StatLearning_Chapter4R_inPython.ipynb.zip)
![ch4_screen_shot](https://cloud.githubusercontent.com/assets/6756310/14274939/21a39cd4-fac9-11e5-918f-46792a0bb379.png)

**Comment by JWarmenhoven** [comment]
Thanks!
I have looked at rpy2 some time ago and gave it a try. The thing is that I run my (dedictated) notebook server on a Raspberry Pi and I believe there is no anaconda installer for Linux ARM architecture. I think I ran into some dependency issues when compiling rpy2. But that being said, it was some time ago so I might have a look again.

**Comment by rlzijdeman** [comment]
Hi, hope you don’t mind me being off topics, but, do, in principle, all R commands work on that Py kernel? Or does it support a specific selection of R libraries?

Best,

Richard
--
Dr. R.L. Zijdeman | CDO | International Institute of Social History | Cruquiusweg 31 | 1019 AT Amsterdam | +31 20 668 5 866

“We don’t care about the distinction between past and present, we’re going to connect them anyway”  — Prof. dr. Diego Ramiro-Fariñas #ESSHC2016

On 05 Apr 2016, at 09:58, Rob Alexander <notifications@github.com<mailto:notifications@github.com>> wrote:


I've also transcribed the Statistical Learning material into Python but only for my own reference. Yours is very elegant and I wish I'd discovered it at the beginning of the course rather than the end.

I noticed that you've gone to the extra step of dumping the R data to file and then loading into the Python environment in Jupyter. In my notes I wanted to have the R and Python code on top of each other for easy reference, so I installed<https://www.continuum.io/blog/developer/jupyter-and-conda-r> an R virtualenv and built<http://www.alfredo.motta.name/create-isolated-jupyter-ipython-kernels-with-pyenv-and-virtualenv/> a "bilingual" Jupyter kernel that handles both languages. So far I've had good results using this version of rpy2<https://anaconda.org/bioconda/rpy2> with Python 3.5 to invoke R magics in Jupyter and intersperse the two languages in the same notebook.

See my attached notebook, in case you find it useful.
StatLearning_Chapter4R_inPython.ipynb.zip<https://github.com/JWarmenhoven/ISLR-python/files/204039/StatLearning_Chapter4R_inPython.ipynb.zip>
[ch4_screen_shot]<https://cloud.githubusercontent.com/assets/6756310/14274939/21a39cd4-fac9-11e5-918f-46792a0bb379.png>

**Comment by JWarmenhoven** [comment]
Here is the way I understand it:

There is the **IRkernel for Jupyter**, which is an interface between Jupyter applications/interfaces and your R installation. So this allows you to run your complete R session in a Jupyter Notebook for example (with inline plotting). This has nothing to do with Python.
http://irkernel.github.io/
Try it out here:
https://tmpnb.org/ (click on button 'New' and select 'R')
Note that there are many more kernels for Jupyter, iPython being the most prominent one.
http://jupyter.readthedocs.org/en/latest/subprojects.html#kernels

**rpy2** is a Python module that lets you interface *between* R and Python in a Python/iPython interpreter session. This is more like 'R in Python' as ralexx' notebook above shows. 

To answer your question:
I am pretty sure that the IRkernel will allow you to use all of the R commands. Not so sure about rpy2.
Guess you are more interested in the IRkernel.

**Comment by rlzijdeman** [comment]
great, thanks for your elaborate answer. There’s this ‘R Markdown’ format, which is plain markdown, but allows you to add R-code within tags… It would be awesome if the future would hold python with R-code or vice versa ;)

Best,

Richard
--
Dr. R.L. Zijdeman | CDO | International Institute of Social History | Cruquiusweg 31 | 1019 AT Amsterdam | +31 20 668 5 866

“We don’t care about the distinction between past and present, we’re going to connect them anyway”  — Prof. dr. Diego Ramiro-Fariñas #ESSHC2016

On 05 Apr 2016, at 13:20, Jordi Warmenhoven <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is the way I understand it:

There is the IRkernel for Jupyter, which is an interface between Jupyter applications/interfaces and your R installation. So this allows you to run your complete R session in a Jupyter Notebook for example (with inline plotting). This has nothing to do with Python.
http://irkernel.github.io/
Try it out here:
https://tmpnb.org/ (click on button 'New' and select 'R')
Note that there are many more kernels for Jupyter, iPython being the most prominent one.
http://jupyter.readthedocs.org/en/latest/subprojects.html#kernels

rpy2 is a Python module that lets you interface between R and Python in a Python/iPython interpreter session. This is more like 'R in Python' as ralexx' notebook above shows.

To answer your question:
I am pretty sure that the IRkernel will allow you to use all of the R commands. Not so sure about rpy2.
Guess you are more interested in the IRkernel.

**Comment by ralexx** [comment]
@JWarmenhoven: you might be in luck should you want to try Anaconda. https://www.continuum.io/content/conda-support-raspberry-pi-2-and-power8-le

There is an issue getting rpy2 to work with Python 3.5, I had to work around. But once fixed, it does offer some conveniences. Anyway, thanks again for publishing your excellent examples from ISL.

**Comment by ralexx** [comment]
@rlzijdeman 

As JWarmenhoven says, rpy2 facilitates interactive sessions e.g. in Jupyter *inter alia*. If that is what you are looking for, you can roll your own Jupyter kernel and use R and Python in the same notebook.
http://www.alfredo.motta.name/create-isolated-jupyter-ipython-kernels-with-pyenv-and-virtualenv/

The `kernel.json` file points to the virtualenv where I have installed a subset of Python 3.5 and R using Miniconda.
https://www.continuum.io/blog/developer/jupyter-and-conda-r

To add to JWarmenhoven's answer, you can install R packages in that virtualenv either using Miniconda or using e.g. an R terminal session called from the R executable in that virtualenv directory. I have done both.
